--- 
eureka: 
  client: 
    serviceUrl: 
      defaultZone: "http://localhost:8761/eureka/"
server: 
  port: 8762
spring: 
  application: 
    name: user-service
  cloud: 
    stream: 
      kafka: 
        binder: 
          brokers: "localhost:9092"
          zkNodes: "localhost:2181"
  sleuth: 
    sampler: 
      percentage: 1.0
  zipkin: 
    base-url: "http://localhost:9411"